### PR TITLE
Create antibioticsforacne

### PR DESCRIPTION
**Pull request by chantekhani89**

### CODE REVIEW

**Comment by chantekhani89** [comment]
I apologize, I am not savvy with coding or GitHub.  I just wanted to create
a new file for our protocol link since the OHDSI site is no longer being
used.  Could you help me with this?

Chante Karimkhani

**Comment by schuemie** [comment]
I recommend the following:

1. Create a subfolder with the name of your study

2. Inside that folder, create a README.md file. In that file, you could post the link to your protocol. I would also put a short description of your study there, and what the status is.

That way, people can click on the subfolder, and the README pops up.

**Comment by chantekhani89** [comment]
When I try to upload new files to create a new folder, it says "uploads are disabled.  File uploads require push access to this repository."  What do I do?

**Comment by chantekhani89** [comment]
When I try to upload new files to create a new folder, it says “uploads are
disabled.  File uploads require push access to this repository.”  What do I
do?

Chante

**Comment by schuemie** [comment]
I've just given you write access to this repo. Please make sure that whatever you do stays within your own folder so it doesn't affect others.

**Comment by ameliaaveritt** [comment]
Great! Thanks.

Amelia Averitt

**Pull request closed without merging**
